### ISSUE TITLE
Make the Dang Thing Poetic

### ISSUE THREAD

**Issue by flosincapite** [Cronenbrogues/cronenbroguelike#51]
Why should the text for item acquisition invariably be the same?

Why should any of the formulaic descriptions lack variety?

Think of Homer: formulaic but with variation.

When, for example, the player acquires an item, there should be a poetic line there to commemorate the occasion.  Use the phonology of the item's name to decide which formulaic poetic line to deploy when describing the event.

**Comment by xmunoz** [comment]
There is no exit criteria defined for this issue :skull:
