### ISSUE TITLE
Tar up the binary to make it executable by default upon download

### ISSUE THREAD

**Issue by xmunoz** [Cronenbrogues/cronenbroguelike#55]
Currently the file metadata isn't preserved by the http download. Add the executable binary to an archive, and have the user download and unarchive the binary, at which point it will be clear that they downloaded an executable.

**Comment by xmunoz** [comment]
Solved with this.

```
tar -cvpf here.tar cronenbroguelike
gzip -c here.tar > here.tar.gz
```

**Comment by xmunoz** [comment]
Website updated with link to the tar-ed archive.

**Comment by flosincapite** [comment]
Thank you <3
