### ISSUE TITLE
Allow multiple themes

### ISSUE THREAD

**Issue by abjose** [Cronenbrogues/cronenbroguelike#63]
I see this is currently a TODO in rooms.py. Would this be as simple as (in addition to making new Rooms) creating a new Floor in game.py, and stitching it into the existing cathedral Floor?

**Comment by flosincapite** [comment]
What I meant by that was that I'd like rooms to be able to have multiple themes. For example, there are rooms that fit the "behemoth" theme but might equally well fit the "cathedral" one.

With respect to your question, I do want to start work on the next floor, too. That should be discussed in another issue, but, in summary, my goal is for the second floor to be accessible from the altar room after the player solves the little puzzle. For that to become possible, we need a couple of things:

1. [a global flag](https://github.com/flosincapite/cronenbroguelike/issues/64) that will add an exit from the altar room upon puzzle completion;
2. a way to make the altar room [unique and guaranteed to spawn](https://github.com/flosincapite/cronenbroguelike/issues/65).

Before any of that happens, I'd like to clean up the implementation of rooms. I hastily and stupidly implemented rooms as class instances when they should just have been types; as it is, the code is littered with `copy.deepcopy` calls and it's really a pain. So I'd like to address [this](https://github.com/flosincapite/cronenbroguelike/issues/66) before any of this other stuff.

**Comment by abjose** [comment]
Sounds good! I'll hold off on making more rooms.

**Comment by flosincapite** [comment]
You can make more rooms if you like! You can use the current `create_room` and make subclasses on the model of the other specialized room types if necessary. The refactor will be pretty transparent (at worst, the name of `create_room` might change).

**Comment by abjose** [comment]
OK, sweet!

**Comment by flosincapite** [comment]
Fixed by #70 . 

Add rooms to your heart's content!
