### ISSUE TITLE
Implement global flag/"switch" system

### ISSUE THREAD

**Issue by flosincapite** [Cronenbrogues/cronenbroguelike#64]
Most games manage quest state, etc. through a global flag system. 

Events should be able to set flags.

There should be a way to register callables that run when a flag is set.

Any part of the game should be able to read the value of flags.

**Comment by flosincapite** [comment]
There is already a stub function for flag setting: https://github.com/flosincapite/cronenbroguelike/blob/main/engine/globals.py#L58

**Comment by xmunoz** [comment]
I don't think we need this.
