### ISSUE TITLE
Allow Rooms to be marked as `unique` and/or `required`

### ISSUE THREAD

**Issue by flosincapite** [Cronenbrogues/cronenbroguelike#65]
Some rooms have to exist for the game to proceed. Some rooms should be unique. When a floor is generated, both of these traits should be consulted, i.e. a floor should contain at most one of each unique room and at least one of each required room.

**Comment by xmunoz** [comment]
#111 implements a solution to this. The `REQUIRED` boolean class attribution is both required and unique. Not ideal, but easier to implement than separate required and unique attributes.
